services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: 'company'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      -  C:\ALLSOFTWARE\youtube_1\SpringGradle\data:/var/lib/mysql
    ports:
      - "3306:3306"
  spring-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
